# Example 001: Radar fixed target

In [1]:
import os

os.chdir(r"C:\Users\malth\OneDrive - Aarhus Universitet\Dokumenter\AAU-Studie\10. semester\NEW GIT\MMARS")
print(os.getcwd())  # Prints current working directory

C:\Users\malth\OneDrive - Aarhus Universitet\Dokumenter\AAU-Studie\10. semester\NEW GIT\MMARS


In [2]:
import numpy as np
import matplotlib.pyplot as plt

import mmars

## Setting up the radar

In [3]:
radar_model_1 = mmars.FmcwRadar(position=np.array([[0,0]]))
radar_model_1.show_parameters()
radar_model_1.radar_to_target_measures()

[[-0.02336045  0.        ]
 [-0.01557363  0.        ]
 [-0.00778682  0.        ]]
[[-0.00292006  0.        ]
 [-0.00097335  0.        ]
 [ 0.00097335  0.        ]
 [ 0.00292006  0.        ]]
Maximum unambiguous range: 99.93 m
Maximum unambiguous IF frequency: 20.00 MHz
Maximum unambiguous velocity: 37.93 m/s
Maximum unambiguous angle: 90.00 degrees
SNR: 10 dB at 10 m
[14.14213562] [7.07106781] [[28.30286416 28.3014875  28.30011097 28.29873458]
 [28.2973527  28.29597603 28.29459951 28.29322311]
 [28.29184337 28.29046671 28.28909018 28.28771379]]


## Setting up the target

In [4]:
target_model_1 = mmars.Target(start_position=np.array([[0,0]]), start_velocity=5.)

target_model_1.generate_trajectory(trajectory_type="sinusoidal")

target_model_1.get_trajectory()

(array([ 0.        ,  0.19998667,  0.39989334,  0.59964006,  0.79914694,
         0.99833417,  1.19712207,  1.39543115,  1.59318207,  1.79029573,
         1.98669331,  2.18229623,  2.37702626,  2.57080552,  2.76355649,
         2.95520207,  3.14566561,  3.33487092,  3.52274233,  3.70920469,
         3.89418342,  4.07760453,  4.25939465,  4.43948107,  4.61779176,
         4.79425539,  4.96880138,  5.14135992,  5.31186198,  5.48023937,
         5.64642473,  5.81035161,  5.97195441,  6.13116852,  6.28793024,
         6.44217687,  6.59384672,  6.74287912,  6.88921445,  7.03279419,
         7.17356091,  7.3114583 ,  7.4464312 ,  7.57842563,  7.70738879,
         7.8332691 ,  7.9560162 ,  8.075581  ,  8.19191568,  8.3049737 ,
         8.41470985,  8.52108022,  8.62404227,  8.72355482,  8.81957807,
         8.9120736 ,  9.00100442,  9.08633496,  9.16803109,  9.24606012,
         9.32039086,  9.39099356,  9.45783999,  9.52090342,  9.5801586 ,
         9.63558185,  9.687151  ,  9.73484542,  9.7

In [5]:
sim = mmars.Simulation(radar_model_1, target_model_1)

sim.run()

Running simulation with <mmars.fmcwRadar.FmcwRadar object at 0x000001ECB928FD00> and <mmars.target.Target object at 0x000001EC990DD9A0>


AttributeError: 'FmcwRadar' object has no attribute '_Simulation__tx_antennas'